In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
 
# Importing Sklearn module and classes
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn import datasets
from sklearn.model_selection import train_test_split

df = pd.read_csv('input_04.csv')

test = pd.read_csv('output_04.csv')
test

X_train = df.drop('Labeling', axis=1)
X_test = test.drop('Labeling', axis=1)
X_train

Y_train = df['Labeling']
Y_test = test['Labeling']
Y_test

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)


lr = LogisticRegression(C=100.0, random_state=1, solver='lbfgs', multi_class='ovr')
 
# Fit the model
#
lr.fit(X_train_std, Y_train)
lr


# Create the predictions
#
Y_predict = lr.predict(X_test_std)
Y_predict
# Use metrics.accuracy_score to measure the score
#print("LogisticRegression Accuracy %.3f" %metrics.accuracy_score(Y_test, Y_predict))


c:\Users\OS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
      dtype=object)

In [27]:
import numpy as np 

X = np.array([[0,2,2], [2,2,0],[3,3,0],[3,2,2],[2,3,2],[2,3,1]])
n_cluster = 3


def init_centers(X, n_cluster):
  # chọn ngẫu nhiên k tâm cụm từ X
  return X[np.random.choice(X.shape[0], n_cluster, replace=False)]

def group_data(X, centers):
    # gom cụm dữ liệu 
    n = X.shape[0]
    y = np.zeros(n)
    # tính khoảng cách từ điểm bất kỳ đến tất cả các tâm cụm
    # xác định điểm đó thuộc cụp = min(dist(X[i] - centers))
    for i in range(n):
        dist = np.linalg.norm(X[i] - centers, axis=1)
        y[i] = np.argmin(dist)
    return y

def update_centers(X, labels, n_cluster):
  centers = np.zeros((n_cluster, X.shape[1]))
  
  for k in range(n_cluster):
    # chọn tất cả các điểm thuộc cụm thứ k
    Xk = X[labels == k, :]

    # chia trung bình công 
    centers[k,:] = np.mean(Xk, axis = 0)
  return centers
    
def kmeans(X,k):
    centers = init_centers(X, n_cluster)
    y = []
    while True:
        y_old = y
        y = group_data(X, centers)
        # kiểm tra đã hội tụ hay chưa
        if np.array_equal(y_old, y):
            break
        # cập nhật tâm cụm
        centerse = update_centers(X, y, n_cluster)
    return (centers, y)


(centers, y) = kmeans(X,n_cluster)
for k in range(n_cluster):
    # chọn tất cả các điểm thuộc cụm thứ k
  Xk = X[y == k, :]
  print('Tâm cụm thứ ',k + 1,': ', centers[k])
  print('Cac diem thuoc cum thu ',k + 1)
  print(str(Xk))


Tâm cụm thứ  1 :  [2 3 2]
Cac diem thuoc cum thu  1
[[3 2 2]
 [2 3 2]
 [2 3 1]]
Tâm cụm thứ  2 :  [0 2 2]
Cac diem thuoc cum thu  2
[[0 2 2]]
Tâm cụm thứ  3 :  [2 2 0]
Cac diem thuoc cum thu  3
[[2 2 0]
 [3 3 0]]


In [28]:
V = [('S', 12), ('A', 7), ('B', 8), ('C', 9), ('D', 6), ('E', 5), ('F', 4), ('G', 10), ('H', 10), ('K', 3), ('M', 9), ('N', 10), ('I', 6), ('J', 0), ('L', 0), ('Z', 8)]
E = [('S', 'A', 5), ('A', 'S', 5), ('S', 'B', 6), ('B', 'S', 6), ('S', 'C', 5), ('C', 'S', 5),
     ('A', 'D', 6), ('D', 'A', 6), ('A', 'E', 7), ('E', 'A', 7), ('B', 'F', 3), ('F', 'B', 3),
     ('B', 'G', 4), ('G', 'B', 4), ('C', 'H', 6), ('H', 'C', 6), ('C', 'K', 4), ('K', 'C', 4),
     ('D', 'M', 5), ('M', 'D', 5), ('D', 'N', 8), ('N','D',8), ('E', 'I', 8), ('I', 'E', 8),
     ('F', 'J', 4), ('J', 'F', 4), ('F', 'L', 4), ('L', 'F', 4), ('K','Z', 2),('Z', 'K', 2)]


In [30]:
class Node:
    def __init__(self, name, parent=None, g = 0, h=0):
        self.name = name
        self.g = g
        self.parent = parent
        self.h = h

    def display(self):
        print(self.name, self.g, self.h)

    def __lt__(self, other):
        if other is None:
            return False
        return self.h + self.g < other.h + other.g

    def checkInArray(self, Close):
        for x in Close:
            if self.equal(x):
                return True
        return False

    def __eq__(self, other):
        if other is None:
            return False
        return self.name == other.name

    def equal(self, other):
        if self.name == other.name:
            return True
        return False

    def checkInPriority(self, c):
        if self is None:
            return False
        return self in c.queue

    def getPath(self):
        print(self.name)
        if self.parent is not None:
            self.parent.getPath()
        else:
            return


from collections import defaultdict
from queue import PriorityQueue
import sys

data = defaultdict(list)
data['S'] = ['A', 5, 'B', 6, 'C', 5, 12]
data['A'] = ['D', 6, 'E', 7, 7]
data['B'] = ['F', 3, 'G', 4, 8]
data['C'] = ['H', 6, 'K', 4, 9]
data['D'] = ['M', 5, 'N', 8, 6]
data['E'] = ['I', 8, 5]
data['F'] = ['J', 4, 'L', 4, 4]
data['G'] = [10]
data['H'] = [10]
data['K'] = ['Z', 2, 3]
data['M'] = [9]
data['N'] = [10]
data['I'] = [6]
data['J'] = [0]
data['L'] = [0]
data['Z'] = [4]

def AStar(S=Node('S'), G=Node('J')):
    Open = PriorityQueue()
    Closed = []
    S.h = data[S.name][-1]
    Open.put(S)
    while True:
        if Open.empty():
            print("Tim kiem that bai")
            return
        O = Open.get()
        Closed.append(O)
        for i in Closed:
            sys.stdout.write(i.name)
        print()
        # print('duyet: ', O.name, O.h)
        if O.equal(G):
            print("Tim kiem thanh cong")
            O.getPath()
            print('Cost: ', O.g)
            return
        i = 0
        while i < len(data[O.name]) - 1:
            name = data[O.name][i]
            g = O.g + data[O.name][i + 1]
            h = data[name][-1]

            tmp = Node(name=name, h=h, g=g)
            tmp.parent = O

            ok1 = tmp.checkInPriority(Open)
            ok2 = tmp.checkInArray(Closed)

            if not ok1 and not ok2:
                Open.put(tmp)
            i += 2

AStar(Node('S'), Node('L'))


S
SA
SAB
SABF
SABFJ
SABFJL
Tim kiem thanh cong
L
F
B
S
Cost:  13
